# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GD_phu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from window1 import Ui_MainWindow

class Ui_QHTT(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def setupUi(self, QHTT):
        QHTT.setObjectName("QHTT")
        QHTT.resize(400, 317)
        self.spinBox = QtWidgets.QSpinBox(QHTT)
        self.spinBox.setGeometry(QtCore.QRect(260, 50, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(6)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(QHTT)
        self.spinBox_2.setGeometry(QtCore.QRect(260, 130, 60, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setMinimum(2)
        self.spinBox_2.setMaximum(6)
        self.spinBox_2.setObjectName("spinBox_2")
        self.So_an = QtWidgets.QLabel(QHTT)
        self.So_an.setGeometry(QtCore.QRect(70, 55, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.So_an.setFont(font)
        self.So_an.setObjectName("So_an")
        self.So_rang_buoc = QtWidgets.QLabel(QHTT)
        self.So_rang_buoc.setGeometry(QtCore.QRect(70, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.So_rang_buoc.setFont(font)
        self.So_rang_buoc.setObjectName("So_rang_buoc")
        self.thoat = QtWidgets.QPushButton(QHTT, clicked = lambda: self.close())
        self.thoat.setGeometry(QtCore.QRect(50, 240, 113, 32))
        self.thoat.setObjectName("thoat")
        self.Chon = QtWidgets.QPushButton(QHTT, clicked = lambda: self.openWindow())
        self.Chon.setGeometry(QtCore.QRect(230, 240, 113, 32))
        self.Chon.setObjectName("Chon")
        self.retranslateUi(QHTT)
        QtCore.QMetaObject.connectSlotsByName(QHTT)

    def retranslateUi(self, QHTT):
        _translate = QtCore.QCoreApplication.translate
        QHTT.setWindowTitle(_translate("QHTT", "Dialog"))
        self.So_an.setText(_translate("QHTT", "Chọn số ẩn"))
        self.So_rang_buoc.setText(_translate("QHTT", "Chọn số ràng buộc"))
        self.thoat.setText(_translate("QHTT", "Thoát"))
        self.Chon.setText(_translate("QHTT", "Chọn"))
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QHTT = QtWidgets.QDialog()
    ui = Ui_QHTT()
    ui.setupUi(QHTT)
    QHTT.show()
    sys.exit(app.exec_())
